"""Regenerate descriptive results from validated records; no model judge."""
import argparse
from collections import defaultdict
import json
import math
from pathlib import Path
import statistics

ROOT = Path(__file__).resolve().parents[1]


def wilson(failures, n):
    if not n:
        return [None, None]
    z = 1.959963984540054
    p = failures / n
    denom = 1 + z * z / n
    center = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return [max(0, center - half), min(1, center + half)]


def summarize(rows):
    groups = defaultdict(list)
    for row in rows:
        groups[(row["codex_version"], row["platform"], row["condition"])].append(row)
    summary = []
    for (version, platform, condition), group in sorted(groups.items()):
        valid = [r for r in group if r["execution_valid"]]
        failures = sum(r["success"] is False for r in valid)
        summary.append({"codex_version": version, "platform": platform, "condition": condition,
                        "n": len(valid), "excluded": len(group) - len(valid), "successes": len(valid) - failures,
                        "failures": failures, "failure_rate": failures / len(valid) if valid else None,
                        "wilson_95": wilson(failures, len(valid)),
                        "median_duration_seconds": statistics.median(r["duration_seconds"] for r in valid) if valid else None,
                        "median_tool_calls": statistics.median(r["tool_calls"] for r in valid) if valid else None})
    return summary


def render(summary):
    lines = ["# MCP inventory experiment results", "", "Generated by `python -m analyzers.report`. These are deterministic protocol replays of actual Codex binaries, **not model inference or a model failure rate**.", "", "| Version | Platform | Condition | Failed invariant / n | Excluded | Median seconds | Tool calls |", "|---|---|---|---:|---:|---:|---:|"]
    for s in summary:
        lines.append(f"| {s['codex_version']} | {s['platform']} | {s['condition']} | {s['failures']}/{s['n']} | {s['excluded']} | {s['median_duration_seconds']} | {s['median_tool_calls']} |")
    lines += ["", "`success` means the inventory outcome remains truthful and explicit. In the named-error control, an explicit failed tool call satisfies the invariant; it is not a successful resource retrieval.", "", "Wilson 95% intervals are saved in the JSON summary for transparency. They do not imply random sampling of users, tasks, models, or MCP implementations. Repeating a deterministic software path checks reproducibility, not general agent reliability.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, action="append")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "reports")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    paths = args.input or sorted((ROOT / "results").glob("*.jsonl"))
    rows = [json.loads(line) for p in paths for line in p.read_text(encoding="utf-8").splitlines() if line]
    summary = summarize(rows)
    outputs = {"mcp-inventory-summary.json": json.dumps(summary, indent=2) + "\n", "mcp-inventory-results.md": render(summary)}
    if args.check:
        for name, content in outputs.items():
            if (args.output_dir / name).read_text(encoding="utf-8") != content:
                raise SystemExit("Report differs: " + name)
        print("Reports match recorded data.")
    else:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        for name, content in outputs.items():
            (args.output_dir / name).write_text(content, encoding="utf-8")
        print("Generated", len(summary), "condition summaries from", len(rows), "runs.")


if __name__ == "__main__":
    main()
